### ISSUE TITLE
Wiki Guide

### ISSUE THREAD

**Issue by madsvodder** [Whimfoome/godot-InventorySystem#2]
Can you make a written guide? I really want to use this, but i have no idea how :)

**Comment by Whimfoome** [comment]
Have you checked the [wiki](https://github.com/Whimfoome/godot-InventorySystem/wiki) of the repository? Also, I am planning to make a video in the future on how to use it. Basically you add Inventory Component to whatever node you want and you call the **toggle_window()** function to access it through the UI at runtime. It's dynamic, so you can add it to literally everything.

**Comment by Whimfoome** [comment]
[Here is a bit of getting started](https://youtu.be/sbhNkrLoHk8)
