### ISSUE TITLE
InventoryComponent add_to_inventory item parameter

### ISSUE THREAD

**Issue by long-boy** [Whimfoome/godot-InventorySystem#3]
Hi, thank you for making this inventory system openly available. I am currently playing around with it. I want to add items to the players inventory when they kill an enemy, called from a function in the players script. The "AddItem.gd" script is quite confusing for me, and I'm not sure how to implement it other than with buttons. I am trying to use The "add_to_inventory" function but am having issues calling it. What exactly do I put in the "item" call? I tried using Item_Apple.gd but it doesnt work, can I add the path somehow without creating a separate node? i.e I want to directly call $InventoryComponent.add_to_inventory(item, amount) in the player script.

Thanks for the help

**Comment by Whimfoome** [comment]
If it's in the player script you can just `$InventoryComponent.add_to_inventory(item, 1)`.

Item parameter can be for example:
`onready var item = load("res://ItemLocation.gd").new()`

**Comment by long-boy** [comment]
Ah thank you! I was missing the load resource
